import { z } from 'zod'

export const propertySchema = z.object({
  name: z.string().min(1, 'Nome é obrigatório'),
  slug: z.string().min(1, 'Slug é obrigatório'),
  code: z.union([z.string(), z.number()]).optional(),
  value: z.string().min(1, 'Valor é obrigatório'),
  summary: z.string().min(1, 'Resumo é obrigatório'),
  type_id: z.string().min(1, 'Tipo do imóvel é obrigatório'),
  description: z.string().min(1, 'Descrição é obrigatória'),
  bedrooms: z.string().refine((v) => !v || Number(v) >= 0, 'Não pode ser negativo'),
  bathrooms: z.string().refine((v) => !v || Number(v) >= 0, 'Não pode ser negativo'),
  suites: z.string().refine((v) => !v || Number(v) >= 0, 'Não pode ser negativo'),
  parkingSpots: z.string().refine((v) => !v || Number(v) >= 0, 'Não pode ser negativo'),
  totalArea: z.string().refine((v) => !v || Number(v) >= 0, 'Não pode ser negativo'),
  privateArea: z.string().refine((v) => !v || Number(v) >= 0, 'Não pode ser negativo'),
  cep: z.string().min(8, 'CEP inválido'),
  state: z.string().min(1, 'Estado é obrigatório'),
  city: z.string().min(1, 'Cidade é obrigatória'),
  neighborhood: z.string().min(1, 'Bairro é obrigatório'),
  street: z.string().min(1, 'Rua é obrigatória'),
  number: z.string().optional(),
  latitude: z.string().min(1, 'Latitude obrigatória'),
  longitude: z.string().min(1, 'Longitude obrigatória'),
  realtorIds: z.array(z.string()).optional(),
  enterpriseId: z.string().optional(),
  priceOnRequest: z.boolean().default(false),
  pricePrefix: z.boolean().default(false),
  highlighted: z.boolean().default(false),
  transactionType: z.enum(['VENDA', 'ALUGUEL']).default('VENDA'),
  applyWatermark: z.boolean().default(true),
  infrastructureIds: z.array(z.string()).default([]),
})

export type PropertyFormData = z.infer<typeof propertySchema>
